name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.20
        uses: actions/setup-go@v2
        id: go
        with:
          go-version: 1.20

      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: build and test
        run: |
          go test -mod=vendor -v -timeout=100s -covermode=count -coverprofile=$GITHUB_WORKSPACE/profile.cov_tmp ./...
          cat $GITHUB_WORKSPACE/profile.cov_tmp | grep -v "mock_" > $GITHUB_WORKSPACE/profile.cov
        working-directory: app
        env:
          GOFLAGS: "-mod=vendor"
          TZ: "Asia/Almaty"
          CGO_ENABLED: 0

      - name: run golangci-lint
        uses: golangci/golangci-lint-action@v2
        env:
          GOFLAGS: "-mod=vendor"
        with:
          version: v1.50.1
          skip-go-installation: true

      - name: submit coverage to codecov
        run: |
          cat $GITHUB_WORKSPACE/profile.cov > $GITHUB_WORKSPACE/coverage.txt
          cd $GITHUB_WORKSPACE
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          GOFLAGS: "-mod=mod"
          CGO_ENABLED: 0

      - name: login to ghcr
        id: docker_login
        if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/') }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: build and push master image
        id: docker_build_master
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ghcr.io/Semior001/newsfeed:master,ghcr.io/Semior001/newsfeed:${{github.sha}}

      - name: build and push tagged (latest) image
        id: docker_build_tagged
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: ghcr.io/Semior001/newsfeed:latest,ghcr.io/Semior001/newsfeed:${{github.ref_name}}
